# Shared base image for all build variants, see Dockerfile
FROM debian:trixie-slim

# Install tools required for the project
RUN apt-get update && apt-get full-upgrade -y \
    && apt-get install -y --no-install-recommends \
        locales \
        curl \
        libsdl2-2.0-0 \
        libsdl3-0 \
        wget \
        gpg \
        ca-certificates \
        tzdata \
        zip \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen

# Set our locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Add the box64 repo, install server dependencies, and cleanup
RUN wget https://ryanfortner.github.io/box64-debs/box64.list -O /etc/apt/sources.list.d/box64.list \
    && wget -qO- https://ryanfortner.github.io/box64-debs/KEY.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/box64-debs-archive-keyring.gpg \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libatomic1 \
        libpulse-mainloop-glib0 \
    && apt-get purge -y wget gpg \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /opt/valheim
