FROM riptidewave93/arm64-valheim:base

# Split out box64 install for better CI experience
RUN apt update \
    && apt install -y \
        box64-rpi5arm64ps16k \
    && apt autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Specific for run Valheim server
EXPOSE 2456-2457/udp
WORKDIR /root
COPY src/bootstrap .
CMD ["/bin/bash", "/root/bootstrap"]
